services:
  - type: web
    name: textoslides
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: textoslides
          property: port
    disk:
      name: textoslides-disk
      mountPath: /opt/render/project/src/temp
      sizeGB: 1
